### ISSUE TITLE
Use base64 on addframe() attribute

### ISSUE THREAD

**Issue by siddharthnaik7** [sole/Animated_GIF#34]
Hello @sole ,

I want to use base 64 data(png) url to create gif image.
How should I use base64 data url?

I am getting following error:
![image](https://cloud.githubusercontent.com/assets/24413681/22931746/d048c26c-f2eb-11e6-9d7e-fc28241dd442.png)

Thanks -Siddharth

**Comment by sole** [comment]
I don't know what you're trying to do. Can you provide a reduced code example?

**Comment by siddharthnaik7** [comment]
Hi, got this issue resolved,
Thanks - Siddharth
